apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-micro-services
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-micro-services
        service: demo-svc
    spec:
      containers:
        - name: demo
          image: davitron/go-micro-services_demo
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
