apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-micro-services
  name: consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-micro-services
    spec:
      containers:
        - name: consul
          image: consul:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8300
            protocol: TCP
          - containerPort: 8400
            protocol: TCP
          - containerPort: 8500
            protocol: TCP